version: "3.9"
services:
  haproxy:
    container_name: haproxy
    image: haproxy:2.6
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy/predator.pem:/etc/ssl/certs/predator.pem:ro
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
      - "8081:8081"
      - "6443:6443"
      - "8080:8080"
      - "32121:32121"